exports.TIME_DELAY_INIT = 3000;

exports.TOKEN_ID = "0.0.3031212";
exports.TOKEN_TOTAL_SUPPLY = 5000;

exports.MINT_BALANCE_PER_NFT = 1000;
exports.MINT_LIMIT_COUNT_PER_WALLET = 20;
exports.NFT_SEND_LIMIT_COUNT_PER_TX = 7;

exports.MINT_STATUS_FREE = 0;
exports.MINT_STATUS_PENDING = 1;
